### ISSUE TITLE
Fix the Files app

### ISSUE THREAD

**Issue by nothaddock** [nothaddock/Pineapple#5]
The Files app is severely bugged. Atleast for me.
I found in Pineapple that: 
- you cannot rename files
- open files without extensions.
And probably many more!

**Comment by haddockdev** [comment]
Closed because the Files app is bugged.
You can get to the prompt by clicking on a file without name.

**Comment by nothaddock** [comment]
Fixed rename bug and the no extension bug seems like it fixed itself.
